### ISSUE TITLE
Ex3: first solution, point 3.

### ISSUE THREAD

**Issue by Andrea-V** [andreamad8/Algo2Problems#2]
It is unclear (to me, at least) which is the index to be binary-searched. The text says "l" (lowercase L), which I think is a typo since "lce_S" does not take l as argument, but only i and j.
I think we need to explain this point a little better.

**Comment by andreamad8** [comment]
Yes, there it could be a bit unclear.
Since we can do an equality check in constant time (using equalS(i,j,l)), the we know that the max length of the possible sub-string is n-1. Therefore we use equalS(i,j,l) with different "l" values. The chosen value follows the binary search technique. 
I hope it can help. As soon as I have time I will try to fix it.
