### ISSUE TITLE
Ex3: Only one of the two can be correct (probably)

### ISSUE THREAD

**Issue by delleciliege** [andreamad8/Algo2Problems#3]
I just modified the solution of the third exercise, the second solution I propose should have been a correction of the first one.
I left the first solution because the result I arrive to are very different from the one of the previous solution, and probably only one of the two can be correct.
Please have a look and check whether there are some mistakes.

**Comment by andreamad8** [comment]
I pull up your solution, I have double checked almost everything (a part of the first long formulas, that we could also reduce). I have commented some part (still present in the latex file), in particular the part about the dimension different form O(n), since we are not really sure about that. 
I would like to ask first to Grossi, then we can also change it.

Anyway, very good job @delleciliege
